import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="header">
        <nav className="navbar navbar-expand-lg navbar-light bg-light fixed-top">
          <div className="container">
            <a className="navbar-brand" href="#">
              Wendy's Burgers
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive"
              aria-controls="navbarResponsive"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarResponsive">
              <ul className="navbar-nav ms-auto">
                <li className="nav-item active">
                  <a className="nav-link" href="#">
                    Home
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    About Wendy's
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Burger Options
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Contact Us
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Wendy's Burgers!</a>
        </h1>

        <p className={styles.description}>Select your options </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Patty Buns Burgers</h2>
            <p>
              A burger is cooked by placing a filling of meat or vegetables in
              between sliced parts of a round bun.
            </p>
          </a>

          <a href="#" className={styles.card}>
            <h2>The Smokin' Patty</h2>
            <p>
              A burger is cooked by placing a filling of meat or vegetables in
              between sliced parts of a round bun.
            </p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Smokin' Burger</h2>
            <p>
              A burger is cooked by placing a filling of meat or vegetables in
              between sliced parts of a round bun.
            </p>
          </a>

          <a href="#" className={styles.card}>
            <h2>The Smokin' Grill</h2>
            <p>
              A burger is cooked by placing a filling of meat or vegetables in
              between sliced parts of a round bun.
            </p>
          </a>
        </div>
      </main>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
      ></link>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"
      ></link>
      <link rel="stylesheet" href="assets/css/style.css"></link>
    </div>
  );
}
